name: AAATailors
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.1.3+3
environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  flutter_native_splash: ^2.1.1
  provider: ^6.0.5
  cached_network_image: ^3.2.3
  google_fonts: ^4.0.4
  google_nav_bar: ^5.0.6
  carousel_slider: ^4.2.1
  font_awesome_flutter: ^10.4.0
  dots_indicator: ^3.0.0
  shared_preferences: ^2.2.1
  connectivity_plus: ^4.0.2
  requests: ^4.7.0
  email_sender: ^1.3.3
  file_picker: ^4.6.1
  razorpay_web: ^1.3.3
  #--------------firebase--------------
  firebase_storage: ^11.0.16
  firebase_auth: ^4.3.0
  firebase_core: ^2.8.0
  google_sign_in: ^5.4.2
  #--------------firebase--------------
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  image_path: "images/app_icon.jpg"
  adaptive_icon_background: "#FFD1A6"
# Splash Screen Settings
flutter_native_splash:
  android_gravity: fill
  fullscreen: true
  background_image: "images/splash1.jpg"
  android_12:
    android_gravity: fill
    fullscreen: true
    image: images/splash1.jpg
    # icon_background_coslor: "#FFD1A6"

flutter:
  uses-material-design: true
  assets:
    - images/
